# -*- coding: utf-8 -*-
"""2102570_Assignment #4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQllLnIGr552XEfH8ZSmq1B1kC2awetl

# Import Library
"""

import os
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
from google.colab import files
import matplotlib.pyplot as plt

"""# ตั้งค่าโมเดล (CNN)

"""

class ElectronicsCNN(nn.Module):
    def __init__(self, num_classes):
        super(ElectronicsCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(64 * 24 * 24, 128)
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(128, num_classes)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

"""# Preprocessing"""

def preprocess_img(img_path):
    img = cv2.imread(img_path)

    # for upload image
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = cv2.resize(img, (96, 96))

    # scale to [0, 1]
    img = img.astype(np.float32) / 255.0
    return img

"""# Loading Data (Image) for training"""

# Loading Data (Image)

class ResistorDataset(Dataset):
    def __init__(self, root_dir):
        self.root_dir = root_dir
        self.classes = sorted([d for d in os.listdir(root_dir) if os.path.isdir(os.path.join(root_dir, d))])[1:]
        # [1:] is delete non class prediction command.
        self.file_list = []
        for idx, cls in enumerate(self.classes):
            cls_path = os.path.join(root_dir, cls)
            for img_name in os.listdir(cls_path):
                if img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
                    self.file_list.append((os.path.join(cls_path, img_name), idx))

    def __len__(self):
        return len(self.file_list)

    def __getitem__(self, idx):
        img_path, label = self.file_list[idx]
        img = preprocess_img(img_path)
        img = np.expand_dims(img, axis=0) # (1, 96, 96)
        return torch.from_numpy(img), torch.tensor(label)

"""# ฟังก์ชันที่ใช้ upload และ ทำนาย"""

def upload_and_predict(model, class_names, device, threshold):
    uploaded = files.upload()

    model.eval()
    for filename in uploaded.keys():
        img_raw = preprocess_img(filename)
        if img_raw is None: continue

        input_tensor = torch.from_numpy(img_raw).unsqueeze(0).unsqueeze(0).to(device)

        with torch.no_grad():
            output = model(input_tensor)
            prob = F.softmax(output, dim=1)
            conf, pred = torch.max(prob, 1)

        plt.imshow(img_raw, cmap='gray')

        # predict Class
        CLASS = class_names[pred.item()]
        if CLASS != "Resistor" or conf.item() < threshold:
            CLASS = "Other"

        # show
        plt.imshow(img_raw, cmap='gray')
        plt.title(f"Predict: {CLASS}\nConf: {conf.item()*100:.2f}%")
        plt.axis('off')
        plt.show()

"""# Main driver code"""

dataset_path = './dataset'

if os.path.exists(dataset_path):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    dataset = ResistorDataset(dataset_path)
    class_names = dataset.classes
    loader = DataLoader(dataset, batch_size=16, shuffle=True)

    # Create Model
    model = ElectronicsCNN(len(class_names)).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    # Training
    print("Training")
    model.train()
    for epoch in range(20): # while Loss >= 0.0050 but I fix it to 20.
        total_loss = 0
        for imgs, labels in loader:
            imgs, labels = imgs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(imgs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"Epoch {epoch+1}/20 - Loss: {total_loss/len(loader):.4f}")

threshold = 0.70
upload_and_predict(model, class_names, device, threshold)